name: micro_habit_runner
description: A micro habit tracking app that helps users take their first step.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_messaging: ^14.6.7
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9
  confetti: ^0.7.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  google_sign_in: ^6.1.5
  google_sign_in_web: ^0.12.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
